version: '3.8'

services:
  web_prod:
    image: nobitran/web_prod
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - "mongodb_prod"
    restart: unless-stopped
    volumes:
      - ./nginx/log:/var/log/nginx/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - prod
  mongodb_prod:
    image: mongo
    ports:
      - 27018:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - prod
networks:
  prod: